### ISSUE TITLE
ProductCatalogItem.StockState enum invalid

### ISSUE THREAD

**Issue by mdg41** [googleapis/python-recommendations-ai#14] opened 2020-10-16 23:16 UTC
`IN_STOCK` and `STOCK_STATE_UNSPECIFIED` both have a value of 0, without specifying `allow_alias=True`.  This is causing deployment errors with protobuf.

The workaround is to specify no binary in requirements.txt:
```
protobuf==3.13.0 --no-binary=protobuf
```

https://github.com/googleapis/python-recommendations-ai/blob/90a06d1edb5b72403c6e039f99c90d1bdeef3337/google/cloud/recommendationengine_v1beta1/types/catalog.py#L167

**Error**
```
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "google/cloud/recommendationengine_v1beta1/types/catalog.proto":
google.cloud.recommendationengine.v1beta1.ProductCatalogItem.StockState: 
"google.cloud.recommendationengine.v1beta1.ProductCatalogItem.IN_STOCK" uses the same enum value as
"google.cloud.recommendationengine.v1beta1.ProductCatalogItem.STOCK_STATE_UNSPECIFIED". If this is
intended, set 'option allow_alias = true;' to the enum definition.
```

**Docs**
https://developers.google.com/protocol-buffers/docs/proto3

**Comment by busunkim96** [comment] 2020-10-19 15:03
@software-dov Could you take a look?

The protos have the `allow_alias` option: https://github.com/googleapis/googleapis/blob/9db36e1646684fc12657d735d9a388df3d5316e4/google/cloud/recommendationengine/v1beta1/catalog.proto#L133-L150 and `allow_alias` is permitted by Python protobuf https://developers.google.com/protocol-buffers/docs/reference/python-generated#enum.

**Comment by matthiasa4** [comment] 2020-11-12 22:16
What's the best way to use the library in the meantime? @mdg41 @busunkim96

**Comment by matthiasa4** [comment] 2020-11-30 20:45
Hi - I'm trying to use this library and having issues with calling a `MessageToDict` method on the `CatalogItem`, giving me:
- `KeyError: 'DESCRIPTOR'`
- `AttributeError: 'DESCRIPTOR'`
errors. Any chance this might be related?

**Comment by busunkim96** [comment] 2020-12-10 22:07
@matthiasa4 That is likely unrelated. Serialization for the messages works a bit differently on the newer clients. See https://proto-plus-python.readthedocs.io/en/latest/messages.html#serialization

Something like `CatalogItem.to_dict(item)` should do the trick (where `item` is the specific instance).

**Comment by matthiasa4** [comment] 2020-12-12 22:05
@busunkim96 that did the trick! Thanks a lot :)

**Comment by danoscarmike** [comment] 2021-03-12 23:31
@software-dov any thoughts on this one?

**Comment by busunkim96** [comment] 2021-03-12 23:36
This is fixed in https://github.com/googleapis/gapic-generator-python/releases/tag/v0.43.0. It should be resolved when the library is re-genenerated.

**Comment by parthea** [comment] 2021-03-27 11:21
I'm going to close this off as the root cause has been determined and the generator has been updated.

**Closed by parthea** 2021-03-27 11:21 UTC
Labels: api: recommendationengine, priority: p2, type: bug
